import {
  defaultSettings,
  freshProgress,
  type Word,
  type Day,
  type Snapshot,
} from "./types";
import { dayKey, shiftDay } from "./study";
const samples = [
  [
    "見込む",
    "みこむ",
    "mikomu",
    "预料；预计；指望",
    "to anticipate; to expect",
    "Verb",
    "今年は売上の増加が見込まれている。",
    "ことしはうりあげのぞうかがみこまれている。",
    "预计今年销售额将增长。",
  ],
  [
    "趣旨",
    "しゅし",
    "shushi",
    "宗旨；主要意思",
    "purpose; main point",
    "Noun",
    "彼の発言の趣旨を理解した。",
    "かれのはつげんのしゅしをりかいした。",
    "我理解了他发言的主旨。",
  ],
  [
    "培う",
    "つちかう",
    "tsuchikau",
    "培养；培育",
    "to cultivate; to nurture",
    "Verb",
    "留学を通じて広い視野を培う。",
    "りゅうがくをつうじてひろいしやをつちかう。",
    "通过留学培养广阔的视野。",
  ],
  [
    "著しい",
    "いちじるしい",
    "ichijirushii",
    "显著的；明显的",
    "remarkable; significant",
    "Adjective",
    "技術の進歩は著しい。",
    "ぎじゅつのしんぽはいちじるしい。",
    "技术进步显著。",
  ],
  [
    "予め",
    "あらかじめ",
    "arakajime",
    "预先；事先",
    "in advance; beforehand",
    "Adverb",
    "予めご連絡ください。",
    "あらかじめごれんらくください。",
    "请事先联系。",
  ],
  [
    "妥協",
    "だきょう",
    "dakyou",
    "妥协；让步",
    "compromise",
    "Noun",
    "品質には妥協しない。",
    "ひんしつにはだきょうしない。",
    "在质量上不妥协。",
  ],
  [
    "促す",
    "うながす",
    "unagasu",
    "催促；促进",
    "to urge; to encourage",
    "Verb",
    "適度な運動は健康を促す。",
    "てきどなうんどうはけんこうをうながす。",
    "适度运动促进健康。",
  ],
  [
    "あえて",
    "あえて",
    "aete",
    "敢于；特意",
    "daringly; deliberately",
    "Adverb",
    "あえて難しい道を選んだ。",
    "あえてむずかしいみちをえらんだ。",
    "特意选择了困难的道路。",
  ],
  [
    "遂げる",
    "とげる",
    "togeru",
    "完成；实现",
    "to accomplish; to achieve",
    "Verb",
    "彼女は大きな進歩を遂げた。",
    "かのじょはおおきなしんぽをとげた。",
    "她取得了很大的进步。",
  ],
  [
    "円滑",
    "えんかつ",
    "enkatsu",
    "圆满；顺利",
    "smooth; harmonious",
    "Adjective",
    "会議は円滑に進んだ。",
    "かいぎはえんかつにすすんだ。",
    "会议顺利进行。",
  ],
  [
    "懸念",
    "けねん",
    "kenen",
    "担心；忧虑",
    "concern; apprehension",
    "Noun",
    "環境への影響が懸念されている。",
    "かんきょうへのえいきょうがけねんされている。",
    "人们担心对环境的影响。",
  ],
  [
    "踏まえる",
    "ふまえる",
    "fumaeru",
    "根据；立足于",
    "to be based on; to take into account",
    "Verb",
    "経験を踏まえて判断する。",
    "けいけんをふまえてはんだんする。",
    "根据经验进行判断。",
  ],
  [
    "手掛かり",
    "てがかり",
    "tegakari",
    "线索；头绪",
    "clue; lead",
    "Noun",
    "解決の手掛かりを見つけた。",
    "かいけつのてがかりをみつけた。",
    "找到了解决的线索。",
  ],
  [
    "取り組む",
    "とりくむ",
    "torikumu",
    "致力于；努力",
    "to tackle; to work on",
    "Verb",
    "新しい課題に取り組む。",
    "あたらしいかだいにとりくむ。",
    "致力于新的课题。",
  ],
  [
    "穏やか",
    "おだやか",
    "odayaka",
    "平静；温和",
    "calm; gentle",
    "Adjective",
    "今日は穏やかな一日だった。",
    "きょうはおだやかないちにちだった。",
    "今天是平静的一天。",
  ],
  [
    "確かめる",
    "たしかめる",
    "tashikameru",
    "确认；查明",
    "to check; to confirm",
    "Verb",
    "出発の時間を確かめる。",
    "しゅっぱつのじかんをたしかめる。",
    "确认出发时间。",
  ],
  [
    "届ける",
    "とどける",
    "todokeru",
    "送达；递交",
    "to deliver",
    "Verb",
    "友達に本を届ける。",
    "ともだちにほんをとどける。",
    "把书送给朋友。",
  ],
  [
    "約束",
    "やくそく",
    "yakusoku",
    "约定；承诺",
    "promise; appointment",
    "Noun",
    "友達との約束を守る。",
    "ともだちとのやくそくをまもる。",
    "遵守与朋友的约定。",
  ],
  [
    "勉強",
    "べんきょう",
    "benkyou",
    "学习",
    "study",
    "Noun",
    "毎日日本語を勉強する。",
    "まいにちにほんごをべんきょうする。",
    "每天学习日语。",
  ],
  [
    "時間",
    "じかん",
    "jikan",
    "时间",
    "time",
    "Noun",
    "時間を大切にする。",
    "じかんをたいせつにする。",
    "珍惜时间。",
  ],
];
export function demoSnapshot(): Snapshot {
  const now = new Date(),
    today = dayKey(now, defaultSettings.timezone);
  const words: Word[] = samples.map((s, i) => {
    const id = `demo-${i}`,
      p = freshProgress(id, "demo");
    if (i < 12) {
      Object.assign(p, {
        status: i < 3 ? "learning" : i < 9 ? "review" : "mastered",
        review_count: 8 + i,
        correct_count: i < 3 ? 4 : 8 + i,
        incorrect_count: i < 3 ? 4 + i : 0,
        interval_days: i < 3 ? 1 : 6,
        repetitions: 2,
        next_review_at: new Date(
          +now + (i < 9 ? -1 : 14) * 86400000,
        ).toISOString(),
        last_reviewed_at: new Date(+now - 2 * 86400000).toISOString(),
        first_learned_at: new Date(+now - 30 * 86400000).toISOString(),
        last_forgotten_at: i < 3 ? now.toISOString() : null,
      });
    }
    return {
      id,
      user_id: "demo",
      word: s[0],
      kana: s[1],
      romaji: s[2],
      meaning_zh: s[3],
      meaning_en: s[4],
      jlpt_level:
        i < 13 ? "N1" : i < 15 ? "N2" : i < 17 ? "N3" : i === 17 ? "N4" : "N5",
      part_of_speech: s[5],
      example_sentence: s[6],
      example_kana: s[7],
      example_translation: s[8],
      notes: "",
      tags: i < 7 ? ["reading", "priority"] : ["daily life"],
      created_at: now.toISOString(),
      progress: { ...p, favorite: i % 5 === 0 },
    };
  });
  const days: Day[] = Array.from({ length: 365 }, (_, i) => {
    const active = i > 350 || i % 9 !== 0;
    const reviews = active ? 12 + ((i * 17) % 51) : 0;
    const n = active ? 5 + (i % 16) : 0;
    return {
      user_id: "demo",
      study_date: shiftDay(today, i - 364),
      new_words: n,
      reviews,
      correct_answers: Math.round((n + reviews) * 0.87),
      incorrect_answers: n + reviews - Math.round((n + reviews) * 0.87),
      duration_ms: (n + reviews) * 27000,
    };
  });
  days[364] = {
    user_id: "demo",
    study_date: today,
    new_words: 12,
    reviews: 38,
    correct_answers: 44,
    incorrect_answers: 6,
    duration_ms: 1920000,
  };
  return { words, days, settings: { ...defaultSettings } };
}
